### PR TITLE
Create Game Form

### PR DESCRIPTION
**Pull request by mhayes853**
Hi all,

This PR simply includes the form and modal used to select game settings and create a game. The only change from the meeting is that now you can select one of the predefined formats (classical, blitz, rapid) in addition to the custom format. To accomodate this I made a small UI change.

Have a look (including the one where the user tries to enter garbage in the stepper fields):
Screenshot 2022-10-25 at 1 21 06 PM
Screenshot 2022-10-25 at 1 21 14 PM
Screenshot 2022-10-25 at 1 21 20 PM
Screenshot 2022-10-25 at 1 21 32 PM

### CODE REVIEW

**Comment by SparklyName** [comment]
LGTM
Also adding some notes primarily to fix running issues.

Unrelated, but here's a license that seems saner than the WTFPL: https://spdx.org/licenses/GLWTPL.html

**Comment by mhayes853** [comment]
Just a question, did you really _need_ to install react router in the root package.json to get things working? 

Additionally, I have to make further amends at some point to the create module script to account for vitest which requires a vite config for testing react hooks, but thanks for adding in the windows fix.

By the way, I consulted the legal team, they advised we keep our current license because the one you provided wishes "good luck". Since we're a soul sucking micromanaging enterprise with employee tracking software installed on microchips inside our employees' brains, wishing "good luck" is something we can't afford to do. Actually, I'm risking my employment by typing this, 50% chance CEO bob is tracking my keystrokes and is monitoring very closely... If it comes down to it, we can just claim that is was @JamesKohls fault...

**Comment by mhayes853** [comment]
Ok... 20th update of the create_module script completed. Let me know when you have to install 20 more dependencies to run simple unit tests (I'm 100% sure it will happen at some point in the _very_ near future). I never thought I would experience worse tooling than XCode, web dev always never ceases to surprise me...

**Comment by mhayes853** [comment]
Fixed some padding consistency issues and an issue where the dropdown menu blocked the steppers (now it only does this on mobile because the small screen sizes don't leave me with any other choice).

Screenshot 2022-10-26 at 2 22 09 PM
Screenshot 2022-10-26 at 2 22 20 PM

**Comment by Eddysunday012** [comment]
Looks good to me!

**Pull request merged**
